# apps/cloudflare-tunnel/values.yaml
existingSecret: cloudflare-tunnel

tunnelID: '90241348-c1cd-46de-9698-0a8466c7425f'
tunnelName: "rackspace"

replicaCount: 1

# Optional tuning
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Keep the tunnel next to your ingress
podLabels:
  app.kubernetes.io/name: cloudflare-tunnel
